#!/usr/bin/env bash
# Rebuild resources/certs/nrb-ca.pem from what NRB is serving today.
#
# Run this when /api/v1/forex/USD starts reporting `tls_chain_incomplete`,
# which means NRB rotated to a certificate the shipped chain no longer covers.
# Needs openssl and outbound HTTPS; run it locally, not on the server.
set -euo pipefail

HOST=www.nrb.org.np
OUT="$(cd "$(dirname "$0")/.." && pwd)/resources/certs/nrb-ca.pem"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "==> Fetching leaf from $HOST"
echo | openssl s_client -connect "$HOST:443" -servername "$HOST" 2>/dev/null \
  | openssl x509 > "$TMP/leaf.pem"

AIA=$(openssl x509 -in "$TMP/leaf.pem" -noout -text \
  | awk '/CA Issuers - URI:/ {sub(/.*URI:/, ""); print; exit}')

if [ -z "$AIA" ]; then
  echo "ERROR: leaf has no CA Issuers URI; find the intermediate by hand." >&2
  exit 1
fi

echo "==> Fetching intermediate from $AIA"
curl -sSf -m 20 -o "$TMP/inter.crt" "$AIA"
# The AIA copy is DER as often as PEM, so normalise.
openssl x509 -inform DER -in "$TMP/inter.crt" -out "$TMP/inter.pem" 2>/dev/null \
  || cp "$TMP/inter.crt" "$TMP/inter.pem"

ROOT_CN=$(openssl x509 -in "$TMP/inter.pem" -noout -issuer \
  | sed 's/.*CN *= *//; s/,.*//')
echo "==> Intermediate chains to root: $ROOT_CN"

# Pull that root out of the system store rather than trusting a download.
SYS=$(openssl version -d | sed 's/OPENSSLDIR: *//; s/"//g')/cert.pem
for CANDIDATE in "$SYS" /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt; do
  [ -f "$CANDIDATE" ] || continue
  awk -v cn="$ROOT_CN" '
    /-----BEGIN CERTIFICATE-----/ {c=""}
    {c = c $0 "\n"}
    /-----END CERTIFICATE-----/ {
      cmd = "openssl x509 -noout -subject 2>/dev/null"
      print c | cmd; close(cmd)
    }' "$CANDIDATE" >/dev/null 2>&1 || true
  python3 - "$CANDIDATE" "$ROOT_CN" "$TMP/root.pem" <<'PY'
import re, subprocess, sys
src, cn, out = sys.argv[1], sys.argv[2], sys.argv[3]
blocks = re.findall(r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----\n",
                    open(src, encoding="utf-8", errors="ignore").read(), re.S)
for b in blocks:
    subj = subprocess.run(["openssl", "x509", "-noout", "-subject"],
                          input=b, capture_output=True, text=True).stdout
    if cn in subj:
        open(out, "w").write(b)
        break
PY
  [ -s "$TMP/root.pem" ] && break
done

if [ ! -s "$TMP/root.pem" ]; then
  echo "ERROR: root '$ROOT_CN' not found in the local trust store." >&2
  exit 1
fi

echo "==> Verifying leaf against the rebuilt chain"
openssl verify -CAfile "$TMP/root.pem" -untrusted "$TMP/inter.pem" "$TMP/leaf.pem"

INTER_SUBJ=$(openssl x509 -in "$TMP/inter.pem" -noout -subject)
INTER_EXP=$(openssl x509 -in "$TMP/inter.pem" -noout -enddate | cut -d= -f2)
ROOT_SUBJ=$(openssl x509 -in "$TMP/root.pem" -noout -subject)
ROOT_EXP=$(openssl x509 -in "$TMP/root.pem" -noout -enddate | cut -d= -f2)

{
  echo "# Certificate chain for $HOST (Nepal Rastra Bank forex API)."
  echo "#"
  echo "# NRB's server sends only its leaf certificate, so OpenSSL cannot build a"
  echo "# path to a root on its own and every request fails with 'unable to get"
  echo "# local issuer certificate' — regardless of the host's CA store. Shipping"
  echo "# the two certificates it omits makes the call work on any server."
  echo "#"
  echo "# Only this one host is ever contacted with this file, so it deliberately"
  echo "# does NOT include the public root store: the trust anchor is pinned to"
  echo "# $ROOT_CN and nothing else."
  echo "#"
  echo "# Regenerated by scripts/refresh-nrb-ca.sh — do not hand-edit."
  echo "#"
  echo "# 1/2 intermediate, expires $INTER_EXP"
  echo "#      $INTER_SUBJ"
  cat "$TMP/inter.pem"
  echo "# 2/2 trust anchor, expires $ROOT_EXP"
  echo "#      $ROOT_SUBJ"
  cat "$TMP/root.pem"
} > "$OUT"

echo "==> Wrote $OUT"
